name: Go-Ethereum test local devnet

services:
  app:
    image: stigi/ethereum-go-image-test:latest
    platform: linux/x86_64 
    environment:
      - ENV_VAR=Local Devnet Test
    networks:
      - devnet
    entrypoint: 
      - geth
      - --dev
      - --http
      - --http.addr=0.0.0.0
      - --http.corsdomain=*
      - --verbosity=5
     
  smart-contract:
    image: stigi/smart-contract-test:latest
    platform: linux/x86_64
    ports:
      - "8545:8545"
    environment:
      - ENV_VAR=Deploy Contracts Test
      - HARDHAT_IGNITION_CONFIRM_DEPLOYMENT=False
    networks:
      - devnet
    depends_on:
      app:
        condition: service_started
    entrypoint: npx hardhat ignition deploy ./ignition/modules/Lock.js --network test

networks:
  devnet:
    driver: bridge
