name: Docker Image and Registry Push CI

on:
  pull_request:
    types: 
      - labeled
    

jobs:
  docker:
    if: ${{ github.event.label.name == 'CI:BUILD' }}
    runs-on: ubuntu-latest

    steps:
    -
      name: Login to Docker Hub
      uses: docker/login-action@v3.4.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_SECRET }}
